INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) 
	VALUES('Az','Az',true);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) 
	VALUES('Adi','Adi',true);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) 
	VALUES('Shah','Shah',true);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) 
	VALUES('Mughal','Mughal',true);

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
	VALUES('Az','ROLE_USER');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
	VALUES('Adi','ROLE_ACCOUNT');
	
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
	VALUES('Shah','ROLE_ADMIN');
	
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
	VALUES('Mughal','ROLE_ADMIN');